import Head from 'next/head'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>X | AleSquare</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='w-full relative bg-gptgray h-screen'>
        {children}
      </main>
    </>
  )
}
